# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRh4-ejC6zGAIMl3BG6DhAAEE38PBouS
"""

from sklearn import datasets
iris = datasets.load_iris()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['']
data = { "weight": [4.17, 5.58, 5.18, 6.11, 4.50, 4.61, 5.17, 4.53, 5.33, 5.14, 4.81, 4.17, 4.41, 3.59, 5.87, 3.83, 6.03, 4.89, 4.32, 4.69, 6.31, 5.12, 5.54, 5.50, 5.37, 5.29, 4.92, 6.15, 5.80, 5.26], "group": ["ctrl"] * 10 + ["trt1"] * 10 + ["trt2"] * 10}
PlantGrowth = pd.DataFrame(data)
#df['target'] = iris.target

plt.hist(df['sepal width (cm)'], color='skyblue', edgecolor='black')

"""I would expect the mean to be higher because the histogram is right skewed."""

mean = np.mean(df['sepal width (cm)'])
median = np.median(df['sepal width (cm)'])
print("mean: ", mean)
print("median: ", median)

print(np.percentile(df['sepal width (cm)'],73))

"""Only 27% of the flowers have a Sepal.Width higher than 3.3 cm."""

plt.scatter(df['sepal width (cm)'], df['sepal length (cm)'], color='blue', edgecolor='black')
plt.xlabel('Sepal Width (cm)')
plt.ylabel('Sepal Length (cm)')
plt.title('Sepal Width vs. Sepal Length')

plt.show()

plt.scatter(df['sepal width (cm)'], df['petal length (cm)'], color='red', edgecolor='black')
plt.xlabel('Sepal Width (cm)')
plt.ylabel('Petal Length (cm)')
plt.title('Sepal Width vs. Petal Length')

plt.show()

plt.scatter(df['sepal width (cm)'], df['petal width (cm)'], color='yellow', edgecolor='black')
plt.xlabel('Sepal Width (cm)')
plt.ylabel('Petal Width (cm)')
plt.title('Sepal Width vs. Petal Width')

plt.show()

plt.scatter(df['sepal length (cm)'], df['petal length (cm)'], color='green', edgecolor='black')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Petal Length (cm)')
plt.title('Sepal Length vs. Petal Length')

plt.show()

plt.scatter(df['sepal length (cm)'], df['petal width (cm)'], color='orange', edgecolor='black')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Petal Width (cm)')
plt.title('Sepal Length vs. Petal Width')

plt.show()

plt.scatter(df['petal length (cm)'], df['petal width (cm)'], color='pink', edgecolor='black')
plt.xlabel('Petal Length (cm)')
plt.ylabel('Petal Width (cm)')
plt.title('Petal Length vs. Petal Width')

plt.show()

"""Based on the scatterplots, petal length and petal width have the strongest relationship, and sepal length and sepal width have the weakest relationship."""

sns.histplot(PlantGrowth['weight'], binwidth=.3, binrange=(3.3,PlantGrowth['weight'].max()))
plt.title('Histogram for Weight Estimate')
plt.xlabel('Value')
plt.ylabel('Frequency')

sns.boxplot(x='group', y='weight', data=PlantGrowth, palette='coolwarm')
plt.show()

"""The IQR for trt1 based off of the boxplots above is approximately 4.85 - 4.2 = .65 and 1.5 * .65 = .975. Thus approximately 97.5% of trt1 weights are blow the minimum trt2 weight."""

sns.barplot(x="group", y="weight", data=PlantGrowth[PlantGrowth['weight'] > 5.5], palette="viridis")

plt.xlabel("Group")
plt.ylabel("Weight")
plt.title("Barplot of Plant Groups (Weight > 5.5)")

plt.show()